name:                design-tools
version:             0.1.0.0
github:              "isovector/design-tools"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/design-tools#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc
- pandoc-types
- cassava
- containers
- bytestring
- vector
- text
- hashable
- directory
- process
- lens
- pretty-show
- mtl
- generic-lens

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src

executables:
  design-tools-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - design-tools

tests:
  design-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - design-tools
